import { describe, it } from 'vitest';

describe('useFlueAgent Vue contracts', () => {
	it.todo('requires a client even while dormant without id');
	it.todo('stays dormant without id and returns empty idle refs');
	it.todo('accepts plain values, refs, computed refs, and getters for name');
	it.todo('accepts plain values, refs, computed refs, and getters for id');
	it.todo('accepts plain values, refs, computed refs, and getters for history');
	it.todo('accepts plain values, refs, computed refs, and getters for live mode');
	it.todo('does not recreate a session when computed option values are unchanged');
	it.todo('replaces the session when id changes');
	it.todo('replaces the session when name changes');
	it.todo('replaces the session when history changes');
	it.todo('replaces the session when live mode changes');
	it.todo('replaces the session when client changes');
	it.todo('returns refs that survive destructuring');
	it.todo('starts observing only after component mount');
	it.todo('does not open streams during server-side setup');
	it.todo('disposes the observer on component unmount');
	it.todo('disposes the observer when an enclosing effectScope stops');
	it.todo('does not mutate returned message arrays in place');
	it.todo('uses shallow snapshot storage so message payloads are not deeply proxied');
	it.todo('loads default history with tail 100');
	it.todo('loads full history with history all');
	it.todo('publishes initial durable history atomically only after hydration completes');
	it.todo('retains optimistic sends made while initial history is loading');
	it.todo('continues live observation from the exact hydration offset');
	it.todo('forwards live mode sse after finite hydration');
	it.todo('keeps historyReady true across live reconnects');
	it.todo('treats initial 404 as an empty new conversation');
	it.todo('attaches from the admission offset after first send for a fresh conversation');
	it.todo('sendMessage rejects without id');
	it.todo('sendMessage adds an optimistic user message immediately');
	it.todo('sendMessage forwards image options to client.agents.send');
	it.todo('sendMessage resolves after admission, not after generation');
	it.todo('sendMessage removes optimistic message and surfaces error when admission fails');
	it.todo('reconciles receipt-before-echo without comparing message text');
	it.todo('reconciles echo-before-receipt by dropping the optimistic duplicate');
	it.todo('keeps optimistic user message position when durable echo arrives late');
	it.todo('keeps durable message order when a send completes during hydration');
	it.todo('preserves send failure state when hydration later completes');
	it.todo('preserves local image data URLs when durable echo redacts image bytes');
	it.todo('builds text and reasoning parts from ordered deltas');
	it.todo('correlates interleaved reasoning deltas by content index');
	it.todo('reconciles streamed assistant content to authoritative message_end content');
	it.todo('provisions an assistant message when a late stream begins at tool_start');
	it.todo('preserves late tool result through terminal reconciliation');
	it.todo('uses finalized tool input while preserving prior result');
	it.todo('drops late text deltas until terminal reconciliation supplies a message');
	it.todo('adds model and usage metadata from turn events');
	it.todo('dedupes redelivered stream events');
	it.todo('accepts restarted event indexes for distinct dispatch contexts');
	it.todo('keeps another local submission pending when one submission becomes idle');
	it.todo('reports streaming when assistant activity arrives before admission');
	it.todo('surfaces terminal submission failure before final idle boundary');
	it.todo('retries transient hydration errors with capped exponential backoff');
	it.todo('retries transient live errors from delivered checkpoint');
	it.todo('short-circuits reconnect backoff when sendMessage wakes the observer');
	it.todo('ignores stale checkpoints from disposed observers after replacement starts');
	it.todo('does not duplicate interrupted partial batches when they are redelivered');
	it.todo('does not cancel server-side work when local observation is disposed');
});

